# This is a basic workflow to help you get started with Actions
name: Test

on:
  push:
  pull_request:

jobs:
  Tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: List available Xcode versions
        run: ls /Applications | grep Xcode
        
      - name: Select Xcode 15.2
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
        
      - name: Show current version of Xcode
        run: xcodebuild -version

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Build and run unit tests
        working-directory: MeetingBar
        shell: bash
        run: |
          set -o pipefail
          xcodebuild \
            -scheme MeetingBar \
            -configuration Debug \
            build test \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
          | xcbeautify
