# This is a basic workflow to help you get started with Actions
name: Lint&Test

on:
  push:
  pull_request:

jobs:
  Lint:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: Run SwiftFormat
        run: swiftformat --lint --disable redundantClosure,trailingClosures,indent --verbose .
  Tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install xcbeautify
        run: brew install xcbeautify
      - name: Run unit tests
        run: xcodebuild -scheme MeetingBar test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcbeautify
